[package]
name = "owa_calendar"
version = "1.0.2"
authors = ["Michael Yurin"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["desktop"] }
manganis = "0.2"
image = { version = "0.24", features = ["ico"] }
notify-rust = { version = "4.11.7", features = ["async"] }
reqwest = { version = "0.12", features = ["cookies", "json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.42", features = ["serde"] }
config = "0.14"
dirs = "5.0"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
