[application]

[desktop]
icon = "assets/favicon.ico"

[bundle]
resources = []

[web.app]

# HTML title tag content
title = "OWA Calendar"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
